### ISSUE TITLE
Review the designs with the volunteers

### ISSUE THREAD

**Issue by joeyvonck** [KA-Huis/space-management-frontends#9]
Joey & Britt talk to the volunteers to assess the designs

**Comment by cyrildewit** [comment]
@joeyvonck what's the objective of this ticket?, which tasks must be done in order to complete this ticket?, what actions have you performed so far? What's the current status? These are some of the questions I came up with while viewing this ticket.

It's important to document this information, so everyone on the current team and new people outside our organisation can jump straight into this project without having to aks you all kinds of questions. You may loose these information overtime, so it's also useful for yourself.

Once we hold the sprint review, we can go to each ticket and find the necessary information to discuss the ticket.

Thank you and I'll see you this evening. Good afternoon.
